import type { Metadata } from "next";
import "@/style/globals.css";
import { hiragino_sans, inter } from "./style/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className={`${inter.variable} ${hiragino_sans.variable}`}>
        {children}
      </body>
    </html>
  );
}
